1756698075201	Sync.LogManager	DEBUG	Flushing file log
1756698075202	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1756698075202	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1756698075204	Sync.LogManager	DEBUG	Log cleanup threshold time: 1755834075204
1756698075208	Sync.LogManager	DEBUG	Done deleting files.
1756698379466	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1756698379466	Sync.Service	DEBUG	User-Agent: Firefox/142.0 (Linux x86_64) FxSync/1.144.0.20250818081258.desktop
1756698379467	Sync.Service	INFO	Starting sync at 2025-09-01 05:46:19 in browser session YwKi1OBOWzel
1756698379467	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1756698379468	Sync.Status	INFO	Resetting Status.
1756698379468	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1756698379469	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1756698379469	FirefoxAccounts	DEBUG	getOAuthToken enter
1756698379469	FirefoxAccounts	TRACE	getCachedToken returning cached token
1756698379469	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1756698379470	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1756698379493	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/197106278/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1756698379494	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1756698379494	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1756698379494	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1756698379494	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1756698379494	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 9932307 ms.
1756698379494	Sync.SyncScheduler	DEBUG	Next sync in 9932307 ms. (why=client-backoff-schedule)
1756698379495	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
